music_app/my_music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :bands, only: [:new, :create, :index, :show, :edit, :update, :destroy]
end

music_app/my_music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/my_music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

end

music_app/my_music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true

  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def self.find_by_credentials(email, password)
    user = self.find_by(email: email)

    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

music_app/my_music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user 
  helper_method :logged_in? 

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token
  end

  def logout_user!
    current_user.reset_session_token
    session[:session_token] = nil
  end
end

music_app/my_music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all 
    render :index
  end

  def show
    @band = Band.find(params[:id])
    if @band 
      render :show
    else
      render :new
    end
  end

  def new
    @band = Band.new
    render :new 
  end
  
  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

music_app/my_music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password])

    if user.nil?
      flash.now[:errors] = ["Incorrect user email/password"]
      render :new
    else  
      login_user!(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    logout_user!
    redirect_to new_session_url
  end
end

music_app/my_music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    if @user 
      render :show
    else
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      # debugger
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

music_app/my_music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/my_music_app/app/views/bands/index.html.erb
  
  <% @bands.each do |band| %>
    <li><%= band.name %></li>
  <% end %>

music_app/my_music_app/app/views/bands/new.html.erb
<section class="page">
  <div class="centered-box">
    <center>
    <h1 class="sign_in_on">Add a new band</h1>

    <%= render 'shared/errors' %>

    <form action="<%= bands_url %>" method="post">
      <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

      <label for="band_name" class="entry_text">Name:</label>
      <input type="text"
        name="band[name]"
        id="band_name"
        value="<%= @band.name %>">
      <br>
      <br>
      <input type="submit" value="Add">
    </form>
    </center>
  </div>
</section>

music_app/my_music_app/app/views/bands/show.html.erb
<section class="page">
  <div class="centered-box">
    <h1>Band: <%= @band.name %></h1>
    
  </div>
 </section>

music_app/my_music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <header><title>My Music App</title></header>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="general">
    <nav class="main-nav">
    <div align="right">
    <% if current_user.nil? %>
      <a href="<%= new_session_url %>">Sign In</a>
      <a href="<%= new_user_url %>">Sign Up</a>
    <% else %>
      <%= current_user.email %>
      <form action="<%= session_url %>" method="post">
        <input
          type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Sign Out">
      </form>
    <% end %>
    </div>
    <div align="left" <h1><a href="<%= users_url %>"> My Music App </a></h1></div>

    </nav>
    <main>
    <%= yield %>
  </body>
</html>

music_app/my_music_app/app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

music_app/my_music_app/app/views/users/new.html.erb
<section class="page">
  <div class="centered-box">
    <center>
    <h1 class="sign_in_on">Create New User</h1>

    <%= render 'shared/errors' %>

    <form action="<%= users_url %>" method="post">
      <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

      <label for="user_email" class="entry_text">Email:</label>
      <input type="text"
        name="user[email]"
        id="user_email"
        value="<%= @user.email %>">
      <br>
      <br>
      <label for="user_password" class="entry_text">Password:</label>
      <input type="password"
        name="user[password]"
        id="user_password"
        value="<%= @user.password %>">
      <br>
      <br>
      <input type="submit" value="Create">
    </form>
    </center>
  </div>
</section>

music_app/my_music_app/app/views/users/show.html.erb
<section class="page">
  <div class="centered-box">
    <h1>You are logged in as <%= @user.email %></h1>
    
  </div>
 </section>